#!/usr/bin/env bash
# Weekly upstream diff helper for kohaku-rs maintainers.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE="${ROOT}/.upstream-cache"
REPORT_DIR="${ROOT}/sync-reports"
DATE="$(date +%Y-%m-%d)"
REPORT="${REPORT_DIR}/${DATE}.md"

KOHAKU_REPO="${KOHAKU_REPO:-https://github.com/ethereum/kohaku.git}"
CLI_REPO="${CLI_REPO:-https://github.com/kassandraoftroy/kohaku-cli.git}"

mkdir -p "${CACHE}" "${REPORT_DIR}"

clone_or_fetch() {
  local name="$1"
  local url="$2"
  local dir="${CACHE}/${name}"
  if [[ -d "${dir}/.git" ]]; then
    git -C "${dir}" fetch --quiet origin
  else
    git clone --quiet "${url}" "${dir}"
  fi
  echo "${dir}"
}

log_range() {
  local dir="$1"
  local label="$2"
  local pin_file="${ROOT}/.upstream-pins/${label}"
  local since=""
  if [[ -f "${pin_file}" ]]; then
    since="$(cat "${pin_file}")"
  fi
  echo "## ${label}" >> "${REPORT}"
  echo "" >> "${REPORT}"
  if [[ -n "${since}" ]]; then
    echo "Commits since pin \`${since:0:12}\`:" >> "${REPORT}"
    echo '```' >> "${REPORT}"
    git -C "${dir}" log --oneline "${since}..HEAD" >> "${REPORT}" || true
    echo '```' >> "${REPORT}"
  else
    echo "No pin file at \`.upstream-pins/${label}\`. Set after first review:" >> "${REPORT}"
    echo "\`git -C ${dir} rev-parse HEAD > .upstream-pins/${label}\`" >> "${REPORT}"
    echo "" >> "${REPORT}"
    echo '```' >> "${REPORT}"
    git -C "${dir}" log --oneline -20 >> "${REPORT}"
    echo '```' >> "${REPORT}"
  fi
  echo "" >> "${REPORT}"
  echo "HEAD: \`$(git -C "${dir}" rev-parse HEAD)\`" >> "${REPORT}"
  echo "" >> "${REPORT}"
}

echo "# Upstream sync report — ${DATE}" > "${REPORT}"
echo "" >> "${REPORT}"
echo "Generated by \`scripts/sync-upstream.sh\`. Review and update [KOHAKU_SYNC.md](../KOHAKU_SYNC.md)." >> "${REPORT}"
echo "" >> "${REPORT}"

KOHAKU_DIR="$(clone_or_fetch kohaku "${KOHAKU_REPO}")"
CLI_DIR="$(clone_or_fetch kohaku-cli "${CLI_REPO}")"

mkdir -p "${ROOT}/.upstream-pins"
log_range "${KOHAKU_DIR}" "ethereum/kohaku"
log_range "${CLI_DIR}" "kassandraoftroy/kohaku-cli"

echo "Wrote ${REPORT}"
